### ISSUE TITLE
How to visulize the degradation embeddings

### ISSUE THREAD

**Issue by Amazingren** [toummHus/HAIR#3]
Dear @toummHus 

Thanks for your impressive work. May I ask how to visualize the tSNR plots of the degradation embeddings?

Could you kindly provide us with the corresponding scripts? It would be super helpful for us.

I am looking forward to hearing from you.

Best regards and many thanks,

**Comment by jin-cao-tma** [comment]
I'm sorry that I didn't save the scripts. However, you can achieve it as follows:
1. For each different degradation, selecting 200 degraded images and combine these 1000 images into a single Dataset.
2. For each degraded image in the Dataset, use the pre-trained model to get the corresponding degradation embedding, and flatten the embeddings into an one-dimentional vector. Finally combine them into a (1000,N) tensor.
3. Use T-SNE to transform the tensor into a shape of (1000,2).
4. Use Seaborn to visualize them 
For the code, please refer https://builtin.com/data-science/tsne-python.

**Comment by Amazingren** [comment]
您的来信已经收到，稍后进行回复，谢谢~

**Comment by Amazingren** [comment]
> I'm sorry that I didn't save the scripts. However, you can achieve it as follows:
> 
> 1. For each different degradation, selecting 200 degraded images and combine these 1000 images into a single Dataset.
> 2. For each degraded image in the Dataset, use the pre-trained model to get the corresponding degradation embedding, and flatten the embeddings into an one-dimentional vector. Finally combine them into a (1000,N) tensor.
> 3. Use T-SNE to transform the tensor into a shape of (1000,2).
> 4. Use Seaborn to visualize them
>    For the code, please refer https://builtin.com/data-science/tsne-python.

Hi @toummHus ,

Thanks a lot for your patience and detailed reply. It reads really helpful.

Best regards and have a nice weekend,
