### ISSUE TITLE
How to plot the tSNE results in your paper?

### ISSUE THREAD

**Issue by progressforever** [toummHus/HAIR#6]
Thanks for your excellent work! I want to plot the tSNE results of different degradation, but my method is not good. 
The input data of tSNE is restoration results?
My code is as follows, thanks~

![image](https://github.com/user-attachments/assets/3b9f657a-9f57-4872-9853-cb31b0246292)

**Comment by jin-cao-tma** [comment]
> Thanks for your excellent work! I want to plot the tSNE results of different degradation, but my method is not good. The input data of tSNE is restoration results? My code is as follows, thanks~
> 
> ![image](https://private-user-images.githubusercontent.com/37981708/376879670-3b9f657a-9f57-4872-9853-cb31b0246292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNTUwODMsIm5iZiI6MTcyOTA1NDc4MywicGF0aCI6Ii8zNzk4MTcwOC8zNzY4Nzk2NzAtM2I5ZjY1N2EtOWY1Ny00ODcyLTk4NTMtY2IzMWIwMjQ2MjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA0NTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOTJmNGMxYjYwN2FmNDg4ZjEwNjk4OTQ5NWI1Nzc3MGJmZjRiODQzMzVhN2VjYWY1YmNlNjVkMTgwMzRjNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IV_OBcz_UxmGcuhBbZVUzSAI53O6IBb2ud_uR8rD4xg)

Maybe you have a misunderstanding. From your code, it seems like you're visualizing the restored images, which is meaningless. In all-in-one settings, **you need to visualize the degradation embeddings**. So you need to firstly get the degradation embeddings from the model you use, and use this code to visualize them

**Comment by jin-cao-tma** [comment]
Please refer to https://github.com/toummHus/HAIR/issues/3
I recommend you to use our model and visualize the GIVs.

**Comment by progressforever** [comment]
Thans for your detailed reply! I visualized it successfully~
